### PR TITLE
fix Symfony validation constraint deprecations

### LINKED ISSUE #548: Fix deprecated Constraint instantiation with options array
We should address this deprecation:

```
  1x: Since symfony/validator 7.3: Passing an array of options to configure the "Symfony\Component\Validator\Constraints\NotNull" constraint is deprecated, use named arguments instead.
    1x in ErrorElementTest::testCall from Sonata\Form\Tests\Validator
```

Its coming from https://github.com/sonata-project/form-extensions/blob/2a75e38508ba7af3f3d865c7bdd8566671a50e3e/src/Validator/ErrorElement.php#L259

maybe we can just unpack the `$options` array on Symfony 7.3+ like

```php
return new $className(...$options);
``` 

assuming that every option on constraint classes is now also defined as a named argument on the constructor? 🤔  ~~What about custom constraints in userland code though...~~ (ok we can only handle it for the `$className = 'Symfony\\Component\\Validator\\Constraints\\'.$name` case)

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

I am targeting this branch, because its BC.

Closes https://github.com/sonata-project/form-extensions/issues/548

## Changelog

```markdown
### Fixed
- Symfony 7.3 deprecations for constraint constructor options array usage
```

### CODE REVIEW

File: src/Validator/ErrorElement.php [hunk 1]
```diff
@@ -256,6 +256,17 @@ private function newConstraint(string $name, array $options = []): Constraint
             ));
         }
 
+        $reflectionClass = new \ReflectionClass($className);
```
Comment (dmaicher) [inline src/Validator/ErrorElement.php]: @VincentLanglet are you familiar with this API? Like calling those magic `assertXYZ` methods on `ErrorElement`. Where is this done or whats the purpose?

Wondering about performance implications for using reflection here :thinking: 

Checked and in my app testsuite this is never called. So not sure about the use-case for this. Supposed to be called only in user-land code?

Comment (VincentLanglet) [reply src/Validator/ErrorElement.php]: No idea about the use case.

This is something which was considered to be deprecated https://github.com/sonata-project/form-extensions/issues/333

But it's used in some other bundle like https://github.com/sonata-project/SonataMediaBundle/blob/426f0689be5e512e5fb9e9b733cd4db997af1a1b/src/Provider/MediaProviderInterface.php#L186

**Review by VincentLanglet — DISMISSED** [review]
I dunno if we shouldn't just return
```
return new $className(...$options);
```
without any check.

Cause if the param doesn't exists, it will still throw an error no ?

**Comment by dmaicher** [comment]
> I dunno if we shouldn't just return
> 
> ```
> return new $className(...$options);
> ```
> 
> without any check.
> 
> Cause if the param doesn't exists, it will still throw an error no ?

yeah indeed. Let's just always go with named arguments :+1:

File: src/Validator/ErrorElement.php (hunk 1 above)
Comment (dmaicher) [reply src/Validator/ErrorElement.php]: Thanks! I will see if I can take a look at it some time soon. Would be good to get rid of it

**Review by VincentLanglet — APPROVED** [review]
