### PR TITLE
Fix deprecated use of `OptionsResolver::setDefault()`

### LINKED ISSUE #540: Deprecated `OptionsResolver::setDefault()`
Hi,

Since Symfony 7.3, `Symfony\Component\OptionsResolver\OptionsResolver::setDefault()` is deprecated in favor of `setOptions()`

See related PR: https://github.com/symfony/symfony/pull/60723

This method is used in BasePickerType, DateRangePickerType & DateTimeRangePickerType.

I'm willing to do a PR, but how do you want to handle BC for SF <7.3 ?

Something like this would it be ok ?

```diff
+ $resolverSetOptionsMethod = \method_exists($resolver, 'setOptions') ? 'setOptions' : 'setDefault';
- $resolver->setDefault('datepicker_options', function (OptionsResolver $datePickerResolver): void {
+ $resolver->{$resolverSetOptionsMethod}('datepicker_options', function (OptionsResolver $datePickerResolver) use ($resolverSetOptionsMethod): void {
	$datePickerResolver->setDefined(array_keys(self::DATEPICKER_ALLOWED_OPTIONS));

	foreach (self::DATEPICKER_ALLOWED_OPTIONS as $option => $allowedTypes) {
		$datePickerResolver->setAllowedTypes($option, $allowedTypes);
	}

	$datePickerResolver->setNormalizer('defaultDate', $this->dateTimeNormalizer());
	$datePickerResolver->setNormalizer('viewDate', $this->dateTimeNormalizer());

	$defaults = $this->getCommonDatepickerDefaults();

	$datePickerResolver->setDefaults($defaults);
-       $datePickerResolver->setDefault('localization', $this->defineLocalizationOptions($defaults['localization'] ?? []));
-       $datePickerResolver->setDefault('restrictions', $this->defineRestrictionsOptions($defaults['restrictions'] ?? []));
-       $datePickerResolver->setDefault('display', $this->defineDisplayOptions($defaults['display'] ?? []));
+	$datePickerResolver->{$resolverSetOptionsMethod}('localization', $this->defineLocalizationOptions($defaults['localization'] ?? []));
+	$datePickerResolver->{$resolverSetOptionsMethod}('restrictions', $this->defineRestrictionsOptions($defaults['restrictions'] ?? []));
+	$datePickerResolver->{$resolverSetOptionsMethod}('display', $this->defineDisplayOptions($defaults['display'] ?? []));
});
```

### PR DESCRIPTION
**Pull request by AirBair**
## Subject

Closes #540

## Changelog

```markdown
### Fixed
- Replace deprecated use of `OptionsResolver::setDefault()` by `OptionsResolver::setOptions()`
```

### CODE REVIEW

File: src/Type/DateTimeRangePickerType.php [hunk 1]
```diff
@@ -30,8 +30,9 @@ public function configureOptions(OptionsResolver $resolver): void
     {
         parent::configureOptions($resolver);
 
-        $resolver->setDefault('field_type', DateTimePickerType::class);
-        $resolver->setDefault('field_options_end', [
```
Comment (dmaicher) [inline src/Type/DateTimeRangePickerType.php]: I actually think those 2 usages were fine, or? its only deprecated to pass a callback to `setDefault` and then configure nested options? :thinking:

File: src/Type/DateRangePickerType.php [hunk 2]
```diff
@@ -26,8 +26,9 @@ public function configureOptions(OptionsResolver $resolver): void
     {
         parent::configureOptions($resolver);
 
-        $resolver->setDefault('field_type', DatePickerType::class);
-        $resolver->setDefault('field_options_end', [
```
Comment (dmaicher) [inline src/Type/DateRangePickerType.php]: same here: those were fine? :thinking:

File: src/Type/DateTimeRangePickerType.php (hunk 1 above)
Comment (AirBair) [reply src/Type/DateTimeRangePickerType.php]: You're right, tests catch my mistake too!

**Comment by dmaicher** [comment]
I will fix this CI error separately 

```
There was 1 error:

1) Sonata\Form\Tests\Bridge\Symfony\DependencyInjection\SonataFormExtensionTest::testTwigBundleLoadParameter
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.build_dir". Did you mean this: "kernel.root_dir"?

/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:99
/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php:58
/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/Container.php:119
/home/runner/work/form-extensions/form-extensions/vendor/symfony/twig-bundle/DependencyInjection/TwigExtension.php:172
/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:81
/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/Compiler/Compiler.php:73
/home/runner/work/form-extensions/form-extensions/vendor/symfony/dependency-injection/ContainerBuilder.php:814
/home/runner/work/form-extensions/form-extensions/vendor/matthiasnoback/symfony-dependency-injection-test/PhpUnit/AbstractContainerBuilderTestCase.php:65
/home/runner/work/form-extensions/form-extensions/tests/Bridge/Symfony/DependencyInjection/SonataFormExtensionTest.php:141
```

its unrelated to your changes

**Comment by AirBair** [comment]
For PHPStan & Psalm failure not sure how you want to handle it, since it's running with SF7.3 it's false positive about always true result.

**Comment by dmaicher** [comment]
> For PHPStan & Psalm failure not sure how you want to handle it, since it's running with SF7.3 it's false positive about always true result.

yes we need to ignore the "always true" errors indeed.

But those errors should be addressed:

```
Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
```

we can probably improve the phpdoc for the methods that return the callbacks?

**Comment by dmaicher** [comment]
You can also rebase. I fixed the unrelated CI errors

**Comment by AirBair** [comment]
Rebase done 👍 

> > But those errors should be addressed:
> 
> ```
> Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
> Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
> Error: Parameter #2 $nested of method Symfony\Component\OptionsResolver\OptionsResolver::setOptions() expects Closure(Symfony\Component\OptionsResolver\OptionsResolver, Symfony\Component\OptionsResolver\Options): void, callable(): mixed given.
> ```
> 
> we can probably improve the phpdoc for the methods that return the callbacks?

I added phpDoc but to be compliant with what [SF expect](https://github.com/yceruto/symfony/blob/89c0b7697052f4a1217d9a16c19ea6867784c2a5/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L416), i had to update the signature of returned callbacks. Hope this is ok.

**Comment by dmaicher** [comment]
> I added phpDoc but to be compliant with what [SF expect](https://github.com/yceruto/symfony/blob/89c0b7697052f4a1217d9a16c19ea6867784c2a5/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L416), i had to update the signature of returned callbacks. Hope this is ok.

Thanks! I had a quick look and actually no need to change the signature :wink: I pushed a fix for phpstan + psalm. Hope it looks ok to you

**Review by dmaicher — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by dmaicher** [comment]
Thanks @AirBair !

**Comment by VincentLanglet** [comment]
Thanks, released in https://github.com/sonata-project/form-extensions/releases/tag/2.5.1

If you're insterested solving deprecations I think there is https://github.com/sonata-project/form-extensions/issues/548 too
